In [ ]:
import numpy as np

aa=np.random.randint(1,99,size=(2, 8))
print(aa.shape)
print(aa.shape[0])
print(aa.shape[1])
print(aa)

print(type(aa))

(2, 8)
2
8
[[67 34 53 25 36 12 93 75]
 [30 22 22 84 52 55 34 56]]
<class 'numpy.ndarray'>


In [ ]:
allMax = -1
subMaxZero = -1
subMaxOne = -1
for i in range(aa.shape[1]) :
  if (aa[0][i] >= subMaxZero ):
    subMaxZero = aa[0][i]
  if (aa[1][i] >= subMaxOne):
    subMaxOne = aa[1][i]

if (subMaxZero >= subMaxOne) :
  allMax = subMaxZero
else:
 allMax = subMaxOne

print('All Max: ' ,allMax)
print('SubMax 0: ' ,subMaxZero)
print('SubMax 1: ' ,subMaxOne)

All Max:  93
SubMax 0:  93
SubMax 1:  84


In [ ]:
b = aa.reshape(2, 2, 4)
print(b.shape)
print(b)

(2, 2, 4)
[[[67 34 53 25]
  [36 12 93 75]]

 [[30 22 22 84]
  [52 55 34 56]]]


In [ ]:
print('새로운 c벡터')

c=b.copy()
c[:,:,:2] = b[:,:,2:]
c[:,:,2:]=b[:,:,:2]
print(c)

새로운 c벡터
[[[53 25 67 34]
  [93 75 36 12]]

 [[22 84 30 22]
  [34 56 52 55]]]


In [ ]:
#slice
import numpy as np
x=np.array([1,2,3,])
x
print(x)

x = [2, 4, 6, 8, 10, 12]
print(x[:3])

[1 2 3]
[2, 4, 6]
